server:
  port: 8080

rocketmq:
  name-server: 150.158.85.93:9876
  producer:
    send-message-timeout: 1000000
spring:

  application:
    name: example-service

  cloud:
    ## nacos 配置
    nacos:
      discovery:
        server-addr: 150.158.85.93:9000
        username: nacos
        password: nacos
        namespace: public

  datasource:
    username: root
    password: Admin12138
    url: jdbc:mysql://150.158.85.93:3308/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis-plus:
  type-aliases-package: com.soft.entity
