server:
  port: 8003
spring:
  application:
    name: petManage-service

  cloud:
    nacos:
      discovery:
        server-addr: 150.158.85.93:9000
        username: nacos
        password: nacos
        namespace: public
