server:
  port: 8001
spring:
  application:
    name: login-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:9000
        username: nacos
        password: nacos
        namespace: public
