server:
  port: 8001
spring:
  application:
    name: login-service

  cloud:
    nacos:
      discovery:
        server-addr: 150.158.85.93:9000
        username: nacos
        password: nacos
        namespace: public

  datasource:
    username: root
    password: Admin12138
    url: jdbc:mysql://150.158.85.93:3308/user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

feign:
  client:
    config:
      store-service:
        connectTimeout: 5000
        readTimeout: 10000